---
# tasks file for external-port-connectivity-validator-server

- name: Create script staging folder for server
  file:
    path: /tmp/simpleserver
    state: directory

- name: Copy server script
  copy:
    src: validation_server.py
    dest: /tmp/simpleserver/validation_server.py
    owner: '{{ opdk_user_name }}'
    group: '{{ opdk_group_name }}'
    mode: 0755

- name: Running validation server at http://{{ private_address }}:{{ check_port }}
  shell: /tmp/simpleserver/validation_server.py "" {{ check_port }}
  async: 1000
  poll: 0
